// Shape masks for the level generator. Each letter is a colour region from
// PALETTE; '.' is outside the shape. Arrows never cross region borders, so a
// region reads as one coloured part of the picture (an apple's leaf, a table leg).
export const PALETTE = {
  r: 'coral',
  g: 'mint',
  b: 'bark',
  y: 'amber',
  s: 'sky',
  l: 'lilac',
  p: 'rose',
}

export const SHAPES = [
  {
    id: 'first-steps',
    name: 'First Steps',
    seed: 11,
    minLen: 2,
    maxLen: 3,
    mask: ['ssss', 'ssss', 'ssss', 'ssss'],
  },
  {
    id: 'crossroads',
    name: 'Crossroads',
    seed: 23,
    minLen: 2,
    maxLen: 4,
    mask: ['sssss', 'sssss', 'sssss', 'sssss', 'sssss'],
  },
  {
    id: 'switchbacks',
    name: 'Switchbacks',
    seed: 37,
    minLen: 3,
    maxLen: 6,
    mask: ['llllll', 'llllll', 'llllll', 'llllll', 'llllll', 'llllll'],
  },
  {
    id: 'diamond',
    name: 'Diamond',
    seed: 41,
    minLen: 2,
    maxLen: 5,
    mask: [
      '...ss...',
      '..ssss..',
      '.ssssss.',
      'ssssssss',
      'ssssssss',
      '.ssssss.',
      '..ssss..',
      '...ss...',
    ],
  },
  {
    id: 'heart',
    name: 'Heart',
    seed: 53,
    minLen: 2,
    maxLen: 6,
    mask: [
      '.ppp..ppp.',
      'pppppppppp',
      'pppppppppp',
      'pppppppppp',
      '.pppppppp.',
      '..pppppp..',
      '...pppp...',
      '....pp....',
    ],
  },
  {
    id: 'apple',
    name: 'Apple',
    seed: 67,
    minLen: 2,
    maxLen: 7,
    mask: [
      '.....b......',
      '.....bggg...',
      '.....bgggg..',
      '..rrrbbrrr..',
      '..rrr..rrr..',
      '..rrr..rrr..',
      '..rrr..rrr..',
      '..rrr..rrr..',
      '..rrr..rrr..',
      '..rrr..rrr..',
      '..rrr..rrr..',
      '..rrr..rrr..',
    ],
  },
  {
    id: 'mug',
    name: 'Mug',
    seed: 79,
    minLen: 2,
    maxLen: 6,
    mask: [
      '.s..s..s...',
      '..s..s..s..',
      'yyyyyyyy...',
      'yyyyyyyyyy.',
      'yyyyyyyy.yy',
      'yyyyyyyy.yy',
      'yyyyyyyyyy.',
      'yyyyyyyy...',
      '.yyyyyy....',
      'bbbbbbbbb..',
    ],
  },
  {
    id: 'table',
    name: 'Table',
    seed: 89,
    minLen: 2,
    maxLen: 7,
    mask: [
      '..llll......',
      '..llll..gg..',
      '..llll.gggg.',
      'bbbbbbbbbbbb',
      'bbbbbbbbbbbb',
      '.bb......bb.',
      '.bb......bb.',
      '.bb......bb.',
      '.bb......bb.',
      '.bb......bb.',
    ],
  },
  {
    id: 'house',
    name: 'House',
    seed: 97,
    minLen: 2,
    maxLen: 7,
    mask: [
      '.....rr.....',
      '....rrrr..bb',
      '...rrrrrr.bb',
      '..rrrrrrrrbb',
      '..rrr..rrr..',
      '..rrr..rrr..',
      '.yyyyyyyyyy.',
      '.yyssyyssyy.',
      '.yyssyyssyy.',
      '.yyyyyyyyyy.',
      '.yyyybbyyyy.',
      '.yyyybbyyyy.',
    ],
  },
  {
    id: 'tree',
    name: 'Tree',
    seed: 101,
    minLen: 2,
    maxLen: 8,
    mask: [
      '....gggg....',
      '..gggggggg..',
      '.gggggggggg.',
      'gggggggggggg',
      'gggggggggggg',
      'gggggggggggg',
      '.gggggggggg.',
      '..gggggggg..',
      '....bbbb....',
      '....bbbb....',
      '....bbbb....',
      '..bbbbbbbb..',
    ],
  },
]
